basePath: /v1/
info:
  contact: {}
  description: 测试
  title: Fabric API
  version: 0.0.1
paths:
  /orgs:
    get:
      consumes:
      - application/json
      description: 读取组织信息
      parameters:
      - description: 组织 DID
        in: path
        name: did
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: 读取组织信息
      tags:
      - org
swagger: "2.0"
