version: "3.9"

services:
  ca-base:
    image: hyperledger/fabric-ca:${FABRIC_CA_VERSION}
    environment:
      - FABRIC_CA_SERVER_HOME=/ca/crypto
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_DEBUG=true
    labels:
      traefik.enable: true
      traefik.docker.network: ${DOCKER_NETWORKS}
    networks:
      - ${DOCKER_NETWORKS}
  
  peer-base:
    image: hyperledger/fabric-peer:${FABRIC_BASE_VERSION}
    environment:
      - CORE_PEER_MSPCONFIGPATH=/peer/msp
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${DOCKER_NETWORKS}
      - FABRIC_LOGGING_SPEC=info
      - CORE_PEER_LISTENADDRESS=0.0.0.0:443
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/peer/tls-msp/signcerts/cert.pem
      - CORE_PEER_TLS_KEY_FILE=/peer/tls-msp/keystore/key.pem
      - CORE_PEER_TLS_ROOTCERT_FILE=/peer/tls-msp/tlscacerts/tls-council-${BASE_URL_SUBST}.pem
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=${COUCHDB_PASSWORD}
      - CORE_PEER_LIMITS_CONCURRENCY_ENDORSERSERVICE=5000000
      - CORE_PEER_LIMITS_CONCURRENCY_DELIVERSERVICE=5000000
      - CORE_PEER_LIMITS_CONCURRENCY_GATEWAYSERVICE=5000000
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    working_dir: /peer
    volumes:
      - /var/run:/host/var/run
    labels:
      traefik.enable: true
      traefik.docker.network: ${DOCKER_NETWORKS}
    networks:
      - ${DOCKER_NETWORKS}

  orderer-base:
    image: hyperledger/fabric-orderer:${FABRIC_BASE_VERSION}
    environment:
      - ORDERER_HOME=/orderer
      - ORDERER_GENERAL_LISTENPORT=443
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/orderer/genesis.block
      - ORDERER_GENERAL_LOCALMSPDIR=/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_CERTIFICATE=/orderer/tls-msp/signcerts/cert.pem
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/orderer/tls-msp/keystore/key.pem
      - ORDERER_GENERAL_TLS_ROOTCAS=[/orderer/tls-msp/tlscacerts/tls-council-${BASE_URL_SUBST}.pem]
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_METRICS_PROVIDER=prometheus
      - ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:9999
      - ORDERER_DEBUG_BROADCASTTRACEDIR=data/logs
      - ORDERER_KAFKA_RETRY_SHORTINTERVAL=1s
      - ORDERER_KAFKA_RETRY_SHORTTOTAL=30s
      - ORDERER_KAFKA_RETRY_LONGINTERVAL=10s
      - ORDERER_KAFKA_RETRY_LONGTOTAL=100s
      - ORDERER_KAFKA_VERBOSE=true
    labels:
      traefik.enable: true
      traefik.docker.network: ${DOCKER_NETWORKS}
    networks:
      - ${DOCKER_NETWORKS}

  couchdb-base:
    image: couchdb:${COUCHDB_VERSION}
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    labels:
      traefik.enable: true
      traefik.docker.network: ${DOCKER_NETWORKS}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5984/"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ${DOCKER_NETWORKS}
  
  kafka-base:
    image: bitnami/kafka:${KAFKA_VERSION}
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper.${BASE_URL}:2181
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_MESSAGE_MAX_BYTES=1048576 # 1 * 1024 * 1024 B
      - KAFKA_REPLICA_FETCH_MAX_BYTES=1048576 # 1 * 1024 * 1024 B
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - KAFKA_LOG_RETENTION_MS=-1
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
    networks:
      - ${DOCKER_NETWORKS}

  cli-base:
    image: hyperledger/fabric-tools:${FABRIC_BASE_VERSION}
    volumes:
        - /var/run/docker.sock:/host/var/run/docker.sock
    networks:
      - ${DOCKER_NETWORKS}

networks:
  ${DOCKER_NETWORKS}:
    external: true
